trigger:
  branches:
    include:
      - master

stages:
  - stage: Validate
    pool:
      vmImage: "ubuntu-latest"
    jobs:
      - job: vt
        displayName: "Validate template"
        steps:
          - task: Pester@0
            displayName: "Check Template syntax"
            inputs:
              scriptFolder: "@{Path='$(System.DefaultWorkingDirectory)/jsonValidation.tests.ps1'; Parameters=@{TemplatePath='.\\server.json'}}"
              resultsFile: "$(System.DefaultWorkingDirectory)/jsonValidation.tests.XML"
              usePSCore: true
              run32Bit: False
          - task: PublishTestResults@2
            displayName: "Publish syntax check result"
            inputs:
              testResultsFormat: "NUnit"
              testResultsFiles: "$(System.DefaultWorkingDirectory)/jsonValidation.tests.XML"
              failTaskOnFailedTests: true
  - template: deployment.template.yml
    parameters:
      azure_resource_group_name:  "ServerProvisionTesting-$(Build.BuildId)"
      subscription_id: "007104fc-5081-48d6-a1ff-aa2e24a50f69"
      application_id: "8ce2d5ed-2d10-4dd0-a703-c380c8e15500"
      tenant_id: "e6af5578-6d03-49e0-af3b-383cf5ec0b5f"
      variableGroup: ServerAutomationDemo
      dependOn: Validate
      environment: demo
      location: UKSouth
