trigger:
  branches:
    include:
      - master

pool:
  vmImage: "ubuntu-latest"

variables:
  - group: ServerAutomationDemo
  - name: azure_resource_group_name
    value: "ServerProvisionTesting-$(Build.BuildId)"
  - name: subscription_id
    value: "007104fc-5081-48d6-a1ff-aa2e24a50f69"
  - name: application_id
    value: "8ce2d5ed-2d10-4dd0-a703-c380c8e15500"
  - name: tenant_id
    value: "e6af5578-6d03-49e0-af3b-383cf5ec0b5f"

steps:
  - task: PowerShell@2
    displayName: "Connect to Azure"
    inputs:
      filePath: "connect-azure.ps1"
      arguments: '-ServicePrincipalPassword "$(ServerAutomationDemo-AppPw)" -SubscriptionId $(subscription_id) -ApplicationId $(application_id) -TenantId $(tenant_id)'
  - task: PowerShell@2
    displayName: "Create Resource Group '$(azure_resource_group_name)'"
    inputs:
      targetType: "inline"
      script: New-AzResourceGroup -Name $(azure_resource_group_name) -Location uksouth -Force
  - task: Pester@0
    displayName: "Test Valid template"
    inputs:
      scriptFolder: "@{Path='$(System.DefaultWorkingDirectory)/server.template.tests.ps1'; Parameters=@{ResourceGroupName='$(azure_resource_group_name)'}}"
      resultsFile: "$(System.DefaultWorkingDirectory)/server.template.tests.XML"
      usePSCore: true
      run32Bit: False
  - task: AzureResourceManagerTemplateDeployment@3
    inputs:
      deploymentScope: "Resource Group"
      azureResourceManagerConnection: "ARM"
      subscriptionId: "$(subscription_id)"
      action: "Create Or Update Resource Group"
      resourceGroupName: $(azure_resource_group_name)
      location: "UK South"
      templateLocation: "Linked artifact"
      csmFile: "server.json"
      csmParametersFile: "server.parameters.json"
      deploymentMode: "Incremental"
      deploymentOutputs: "arm_output"
  - task: Pester@0
    displayName: "Test Deployment results"
    inputs:
      scriptFolder: "@{Path='$(System.DefaultWorkingDirectory)/server.infrastructure.tests.ps1'; Parameters=@{ArmDeploymentJsonOutput='$(arm_output)'}}"
      resultsFile: "$(System.DefaultWorkingDirectory)/server.infrastructure.tests.XML"
      usePSCore: true
      run32Bit: False
  - task: PowerShell@2
    displayName: "Get contents of $(azure_resource_group_name)"
    inputs:
      targetType: "inline"
      script: Get-AzResourceGroup -Name $(azure_resource_group_name) 
  - task: PublishTestResults@2
    inputs:
      testResultsFormat: "NUnit"
      testResultsFiles: "$(System.DefaultWorkingDirectory)/server.infrastructure.tests.XML"
      failTaskOnFailedTests: true

  - task: PublishTestResults@2
    inputs:
      testResultsFormat: "NUnit"
      testResultsFiles: "$(System.DefaultWorkingDirectory)/server.template.tests.XML"
      failTaskOnFailedTests: true
